# Generated by Django 4.2.7 on 2024-05-23 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0002_bucket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bucket',
        ),
    ]
