# Generated by Django 5.0.6 on 2024-05-17 13:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilm', '0007_alter_course_description_alter_course_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
    ]
