# Generated by Django 5.0.6 on 2024-05-19 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilm', '0012_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='course',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
    ]
